Replace watchdogs with ping
dashpay/sentinel pull request #17
Opened 2017-06-07 21:55 UTC by gladcow

Rationale: Watchdogs have proved quite problematic. We should be able to replace them by integrating sentinel information into Masternode ping objects. Need to use new rpc call for sentinel to update its timestamp and version.

This requires changes to both dashcore and sentinel (dashcore PR#1491 with the same name). The changes are made in a backward compatible way so that dashcore and sentinel do not necessarily have to be upgraded at the same time. 

Changes  for sentinel:
 check if dashd supports sentinel ping, checking if the governance info has the flag "hassentinelping";
 if ping supported call sentinel ping rpc command on each run and disable watchdog creation, otherwise use current behavior (ie. create watchdogs)

2017-06-14 12:34 UTC, tgflynn requested changes

2017-06-14 12:34 UTC, tgflynn commented on bin/sentinel.py
> +    # delete expired watchdogs
I don't think it's a good idea to duplicate the wd expiration code here.  Needs a slightly better design to avoid code duplication, I think.

2017-06-14 12:36 UTC, tgflynn commented
Since this is for v0.12.2.x I think it should be merged to a new development branch rather than to master.

@nmarley - Thoughts ?

2017-06-15 02:03 UTC, nmarley commented
@tgflynn Yes, it should probably be merged into another branch for 12.2, pending more review/refactor I think.

2017-06-20 03:29 UTC, nmarley requested changes
Possible to remove the WD expiration loop in the `sentinel_ping` method? Other than that looks ok to me. We might want to wait to merge this into master 'til we release 12.2, or merge it into a different branch as Tim suggested.

2017-06-20 03:29 UTC, nmarley commented on bin/sentinel.py
> +    # delete expired watchdogs
I agree, should remove the WD expiration loop here.

2017-06-20 03:29 UTC, nmarley commented on lib/config.py
> +sentinel_version = 2
I think this should be fine for now, but we might wanna discuss a versioning scheme for Sentinel and how we wanna handle it.

2017-06-20 11:53 UTC, UdjinM6 commented on lib/config.py
> +sentinel_version = 2
Since this also impacts dashd side I'd rather discuss versioning sooner than later.

2017-06-28 14:46 UTC, nmarley approved these changes

2017-06-28 15:01 UTC, tgflynn commented
utACK

2017-09-14 09:10 UTC, merged